"""Turn a choice analysis into a walkthrough - as a mod, and as a document.

The mod is a single `.rpy` dropped into the game's folder. It wraps
`renpy.exports.menu`, which is what `Menu.execute` calls on both Ren'Py 7 and 8
with the identical signature `(choices, set_expr, args, kwargs,
item_arguments)`. Each entry in `choices` is `(caption, condition, index)`
where `index` is the option's position in the original `menu` statement - the
same index the analyser recorded - so annotations line up exactly.

Menus are identified at runtime by `renpy.get_filename_line()`, which returns
the location of the executing statement. Matching that against the AST node's
own filename and line number is unambiguous, unlike matching on caption text
which breaks as soon as a game reuses "Yes" and "No".

The generated file has to run under Python 2 as well, because Ren'Py 7 games
are still common - so no f-strings, and every string literal is written as an
escaped `u"..."`.
"""

from __future__ import annotations

import html
import json
from datetime import datetime
from pathlib import Path

from ...core.fsutil import atomic_write
from .analyze import Analysis, Choice, MenuPoint, looks_like_ending

MOD_FILENAME = "nodex_walkthrough.rpy"
#: Late enough to win against anything the game sets up itself.
INIT_PRIORITY = 1999
DEFAULT_COLOUR = "#7fdc7f"


def _py_string(value: str) -> str:
    """Emit a Python 2/3 compatible unicode literal."""
    out = []
    for char in value:
        if char == "\\":
            out.append("\\\\")
        elif char == '"':
            out.append('\\"')
        elif char == "\n":
            out.append("\\n")
        elif char == "\r":
            out.append("\\r")
        elif char == "\t":
            out.append("\\t")
        elif 32 <= ord(char) < 127:
            out.append(char)
        else:
            out.append("\\u%04x" % ord(char))
    return 'u"%s"' % "".join(out)


def _escape_renpy_text(value: str) -> str:
    """Neutralise Ren'Py's text markup in generated captions.

    `[name]` interpolates a variable and `{b}` starts a tag; a variable value
    containing either would corrupt the menu at best and crash it at worst.
    """
    return value.replace("[", "[[").replace("{", "{{")


def annotation_for(choice: Choice, colour: str = DEFAULT_COLOUR) -> str:
    """The text appended to a choice's caption in game."""
    parts = [effect.describe() for effect in choice.effects]
    for target in choice.jumps + choice.calls:
        parts.append("-> " + target)
    if not parts:
        parts = [effect.describe() for effect in choice.downstream[:2]]
    if not parts:
        return ""

    text = ", ".join(parts[:4])
    return "{color=%s}(%s){/color}" % (colour, _escape_renpy_text(text))


def build_annotations(analysis: Analysis) -> dict[str, dict[int, str]]:
    """Map `filename:line` to per-index annotation text."""
    table: dict[str, dict[int, str]] = {}
    for menu in analysis.menus:
        entries = {}
        for choice in menu.choices:
            text = annotation_for(choice)
            if text:
                entries[choice.index] = text
        if entries:
            table[menu.key] = entries
    return table


def build_mod(analysis: Analysis, colour: str = DEFAULT_COLOUR) -> str:
    """Render the walkthrough mod's source."""
    table = build_annotations(analysis)

    lines = [
        "# Generated by Nodex on %s." % datetime.now().strftime("%Y-%m-%d %H:%M"),
        "#",
        "# Annotates each menu choice with the variables it changes and where it",
        "# leads. Delete this file to remove the mod - it changes nothing else.",
        "#",
        "# %d menu(s) annotated across %d script(s)."
        % (len(table), analysis.scripts_read),
        "",
        "init %d python:" % INIT_PRIORITY,
        "",
        "    _nodex_annotations = {",
    ]

    for key in sorted(table):
        entries = table[key]
        rendered = ", ".join(
            "%d: %s" % (index, _py_string(entries[index])) for index in sorted(entries)
        )
        lines.append("        %s: {%s}," % (_py_string(key), rendered))

    lines.extend(
        [
            "    }",
            "",
            "    def _nodex_annotate(items):",
            "        try:",
            "            filename, line = renpy.get_filename_line()",
            "        except Exception:",
            "            return items",
            "",
            '        table = _nodex_annotations.get("%s:%s" % (filename, line))',
            "        if not table:",
            "            return items",
            "",
            "        annotated = []",
            "        for entry in items:",
            "            try:",
            "                caption, condition, value = entry",
            "            except Exception:",
            "                annotated.append(entry)",
            "                continue",
            "            note = table.get(value)",
            "            if note and caption:",
            '                caption = caption + " " + note',
            "            annotated.append((caption, condition, value))",
            "        return annotated",
            "",
            "    def _nodex_menu(items, *args, **kwargs):",
            "        try:",
            "            items = _nodex_annotate(items)",
            "        except Exception:",
            "            pass",
            "        return _nodex_original_menu(items, *args, **kwargs)",
            "",
            "    # Patch once, even if this init block is re-entered.",
            '    if not getattr(renpy.exports, "_nodex_patched", False):',
            "        _nodex_original_menu = renpy.exports.menu",
            "        renpy.exports.menu = _nodex_menu",
            "        renpy.exports._nodex_patched = True",
            "",
        ]
    )

    return "\n".join(lines)


def install_mod(
    analysis: Analysis, game_dir: Path | str | None = None, colour: str = DEFAULT_COLOUR
) -> Path:
    """Write the mod into the game's folder. Returns the path written."""
    target = Path(game_dir) if game_dir is not None else analysis.game_dir
    destination = target / MOD_FILENAME
    atomic_write(destination, build_mod(analysis, colour).encode("utf-8"))
    _clear_stale_compiled(destination)
    return destination


def _clear_stale_compiled(mod_path: Path) -> None:
    """Drop a previously compiled copy so Ren'Py recompiles the new source."""
    compiled = mod_path.with_suffix(".rpyc")
    if compiled.exists():
        try:
            compiled.unlink()
        except OSError:
            pass


def uninstall_mod(game_dir: Path | str) -> list[Path]:
    """Remove the mod and its compiled form. Returns what was deleted."""
    game_dir = Path(game_dir)
    removed = []
    for candidate in (game_dir / MOD_FILENAME, (game_dir / MOD_FILENAME).with_suffix(".rpyc")):
        if candidate.exists():
            try:
                candidate.unlink()
                removed.append(candidate)
            except OSError:
                pass
    return removed


# ---------------------------------------------------------------------------
# Static document
# ---------------------------------------------------------------------------


def _choice_rows(menu: MenuPoint) -> str:
    rows = []
    for choice in menu.choices:
        effects = "".join(
            '<span class="eff">%s</span>' % html.escape(effect.describe())
            for effect in choice.effects
        )
        routes = "".join(
            '<span class="route %s">%s</span>'
            % ("ending" if looks_like_ending(target) else "", html.escape(target))
            for target in choice.jumps + choice.calls
        )
        downstream = ""
        if not effects and choice.downstream:
            downstream = '<span class="later">later: %s</span>' % html.escape(
                ", ".join(e.describe() for e in choice.downstream[:3])
            )
        if not (effects or routes or downstream):
            effects = '<span class="none">no effect</span>'

        condition = (
            '<span class="cond">if %s</span>' % html.escape(choice.condition)
            if choice.condition
            else ""
        )

        rows.append(
            "<tr><td class=\"cap\">%s%s</td><td>%s%s%s</td></tr>"
            % (
                html.escape(choice.caption) or "<em>(blank)</em>",
                condition,
                effects,
                routes,
                downstream,
            )
        )
    return "".join(rows)


def build_html(analysis: Analysis, title: str = "Walkthrough") -> str:
    """Render a self-contained walkthrough document."""
    # Every menu with options is included. A choice that only leads to
    # different dialogue still matters to a reader, and filtering those out
    # would drop most of the choice points in some games.
    menus = [menu for menu in analysis.menus if menu.choices]
    blocks = []

    for menu in menus:
        heading = menu.label or "(no label)"
        blocks.append(
            '<section class="menu%s" data-search="%s" data-meaningful="%d">'
            '<h3>%s <span class="loc">%s:%d</span></h3>'
            "<table>%s</table></section>"
            % (
                "" if menu.meaningful else " minor",
                html.escape(
                    " ".join(
                        [heading, menu.filename]
                        + [c.caption for c in menu.choices]
                        + [e.variable for c in menu.choices for e in c.effects]
                    ).lower()
                ),
                1 if menu.meaningful else 0,
                html.escape(heading),
                html.escape(menu.filename),
                menu.linenumber,
                _choice_rows(menu),
            )
        )

    variables = "".join(
        "<li><b>%s</b> <span>%d</span></li>" % (html.escape(name), count)
        for name, count in analysis.tracked_variables[:40]
    )

    return _HTML_TEMPLATE % {
        "title": html.escape(title),
        "generated": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "menu_count": len(analysis.meaningful_menus),
        "total_menus": len(menus),
        "script_count": analysis.scripts_read,
        "variable_count": len(analysis.variables),
        "variables": variables,
        "menus": "".join(blocks),
    }


_HTML_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%(title)s - Nodex walkthrough</title>
<style>
:root{color-scheme:dark;--bg:#12131a;--panel:#191b25;--border:#2c3040;--text:#e6e8f0;
--muted:#8b90a6;--accent:#6ea8fe;--ok:#7fdc7f;--warn:#fbbf24}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--text);
font-family:"Segoe UI",system-ui,sans-serif;font-size:14px;line-height:1.5}
header{padding:22px 28px;border-bottom:1px solid var(--border);background:var(--panel);
position:sticky;top:0;z-index:5}
h1{margin:0 0 4px;font-size:19px}
.sub{color:var(--muted);font-size:13px}
.stats{display:flex;gap:22px;margin-top:12px;flex-wrap:wrap}
.stats div{font-size:12px;color:var(--muted)}
.stats b{display:block;font-size:19px;color:var(--text)}
.controls{margin-top:14px;display:flex;gap:14px;align-items:center;flex-wrap:wrap}
.controls input[type=search]{flex:1 1 280px;min-width:0;max-width:440px;padding:8px 12px;
border-radius:7px;border:1px solid var(--border);background:var(--bg);color:var(--text);font:inherit}
.controls input:focus{outline:none;border-color:var(--accent)}
.controls label{color:var(--muted);font-size:13px;display:flex;gap:6px;align-items:center;cursor:pointer}
.menu.minor h3{opacity:.72}
main{padding:22px 28px;display:grid;grid-template-columns:1fr 250px;gap:26px;align-items:start}
@media(max-width:900px){main{grid-template-columns:1fr}}
.menu{background:var(--panel);border:1px solid var(--border);border-radius:9px;
padding:14px 16px;margin-bottom:14px}
.menu h3{margin:0 0 10px;font-size:14px;display:flex;justify-content:space-between;gap:10px}
.loc{color:var(--muted);font-weight:400;font-family:Consolas,monospace;font-size:11px}
table{width:100%%;border-collapse:collapse}
td{padding:6px 8px;border-top:1px solid var(--border);vertical-align:top}
td.cap{width:44%%;font-weight:600}
.cond{display:block;font-weight:400;color:var(--warn);font-size:11px;font-family:Consolas,monospace}
.eff,.route,.later,.none{display:inline-block;margin:2px 5px 2px 0;padding:2px 8px;
border-radius:99px;font-size:12px;font-family:Consolas,monospace}
.eff{background:#7fdc7f1f;color:var(--ok)}
.route{background:#6ea8fe1f;color:var(--accent)}
.route.ending{background:#fbbf241f;color:var(--warn)}
.later{background:#ffffff0d;color:var(--muted)}
.none{color:var(--muted)}
aside{position:sticky;top:150px;background:var(--panel);border:1px solid var(--border);
border-radius:9px;padding:14px 16px}
aside h2{margin:0 0 10px;font-size:12px;text-transform:uppercase;letter-spacing:1px;color:var(--muted)}
aside ul{list-style:none;margin:0;padding:0;max-height:60vh;overflow:auto}
aside li{display:flex;justify-content:space-between;padding:3px 0;font-family:Consolas,monospace;font-size:12px}
aside span{color:var(--muted)}
.hidden{display:none}
</style></head><body>
<header>
<h1>%(title)s</h1>
<div class="sub">Generated by Nodex on %(generated)s</div>
<div class="stats">
<div><b>%(menu_count)d</b>with consequences</div>
<div><b>%(total_menus)d</b>choice points</div>
<div><b>%(script_count)d</b>scripts read</div>
<div><b>%(variable_count)d</b>variables tracked</div>
</div>
<div class="controls">
<input id="q" type="search" placeholder="Filter by choice, label or variable...">
<label><input id="only" type="checkbox"> Only choices with consequences</label>
</div>
</header>
<main>
<div id="list">%(menus)s</div>
<aside><h2>Most-affected variables</h2><ul>%(variables)s</ul></aside>
</main>
<script>
var box=document.getElementById('q');
var only=document.getElementById('only');
var items=[].slice.call(document.querySelectorAll('.menu'));
function apply(){
  var needle=box.value.trim().toLowerCase();
  var strict=only.checked;
  items.forEach(function(el){
    var hide=(needle && el.dataset.search.indexOf(needle)<0)
          || (strict && el.dataset.meaningful!=='1');
    el.classList.toggle('hidden', hide);
  });
}
box.addEventListener('input',apply);
only.addEventListener('change',apply);
</script>
</body></html>
"""


def write_html(analysis: Analysis, destination: Path | str, title: str = "Walkthrough") -> Path:
    destination = Path(destination)
    atomic_write(destination, build_html(analysis, title).encode("utf-8"))
    return destination


def build_json(analysis: Analysis) -> str:
    """Machine-readable dump, for diffing between game versions."""
    return json.dumps(
        {
            "game_dir": str(analysis.game_dir),
            "scripts_read": analysis.scripts_read,
            "menus": [
                {
                    "key": menu.key,
                    "label": menu.label,
                    "filename": menu.filename,
                    "line": menu.linenumber,
                    "choices": [
                        {
                            "index": choice.index,
                            "caption": choice.caption,
                            "condition": choice.condition,
                            "effects": [e.describe() for e in choice.effects],
                            "routes": choice.jumps + choice.calls,
                            "downstream": [e.describe() for e in choice.downstream],
                        }
                        for choice in menu.choices
                    ],
                }
                for menu in analysis.menus
            ],
            "variables": dict(analysis.tracked_variables),
        },
        indent=2,
    )
